POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Java"
}

###

GET http://localhost:3333/courses


###
GET http://localhost:3333/courses/7869c9dc-3514-4e4d-95cc-e24d789e7cf4

###
DELETE http://localhost:3333/courses/40b5424f-6c18-4155-9794-37582a7fe6cb